// Catalogue des exercices (spécification, section 6.3) : données seules, sans logique.
//
// Chaque exercice : `id` (référencé par les circuits, à ne jamais renommer), `code` (repère du
// livre d'exercices, facultatif), `name`, `instruction` (consigne courte affichée pendant la
// séance), `description` (exécution détaillée, affichée dans le détail d'un circuit) et `muscles`.
// Son illustration est assets/exercises/{id}.svg (section 6.2).

export const EXERCISES = [
  {
    id: 'pompes',
    code: 'A',
    name: 'Pompes',
    instruction: 'Corps gainé, poitrine près du sol.',
    description: 'Mains au sol écartées d’environ deux largeurs d’épaules, en appui sur la pointe des pieds. Le corps reste droit et gainé de la tête aux talons. Fléchissez les bras en inspirant jusqu’à ce que la poitrine frôle le sol, puis remontez en tendant les bras et en soufflant.',
    muscles: 'Pectoraux, triceps, épaules',
  },
  {
    id: 'pompes-chaises',
    code: 'A1',
    name: 'Pompes entre chaises',
    instruction: 'Corps gainé, descendez entre les chaises.',
    description: 'Mains sur deux chaises écartées d’environ deux largeurs d’épaules, pieds posés sur une troisième. Corps droit et gainé, sans cambrer. Descendez le plus bas possible entre les chaises en inspirant, sans forcer sur les épaules, puis remontez bras tendus en soufflant. Prenez des assises plates et fermes ; si les chaises glissent, posez-les sur un tapis ou ajoutez des patins antidérapants.',
    muscles: 'Pectoraux, triceps, épaules',
  },
  {
    id: 'pompes-chaises-pieds-meuble',
    code: 'A2',
    name: 'Pompes entre chaises, pieds sur meuble',
    instruction: 'Pieds en hauteur, plongez entre les chaises.',
    description: 'Mains à plat sur deux chaises écartées d’environ deux largeurs d’épaules, pieds posés sur un support d’environ 1 m (meuble, rebord de fenêtre, espalier). Placez les chaises de sorte que le corps reste droit. Descendez le plus bas possible en inspirant, puis remontez jusqu’à tendre les bras en soufflant. Ne cambrez jamais, même quand l’effort devient dur. Protégez le meuble avec une serviette.',
    muscles: 'Pectoraux, épaules, triceps',
  },
  {
    id: 'pompes-mains-support-45cm',
    code: 'A3',
    name: 'Pompes mains sur support de 45 cm',
    instruction: 'Poitrine au contact du support, dos droit.',
    description: 'Mains écartées d’environ 40 cm sur un support haut d’environ 45 cm (tabouret, banc, meuble ou deux chaises côte à côte), pieds au sol. Descendez en inspirant jusqu’à ce que la poitrine touche le support, puis revenez bras tendus en soufflant. Ne cambrez pas : mieux vaut garder les fesses légèrement en arrière.',
    muscles: 'Milieu de la poitrine, triceps',
  },
  {
    id: 'pompes-mains-support-35cm',
    code: 'A4',
    name: 'Pompes mains sur support de 35 cm',
    instruction: 'Poitrine au contact du support, dos droit.',
    description: 'Même technique que les pompes sur support de 45 cm, mains écartées d’environ 40 cm, mais sur un support plus bas, d’environ 35 cm : l’exercice devient plus difficile. Pieds au sol, corps droit. Descendez en inspirant jusqu’à ce que la poitrine touche le support, puis remontez bras tendus en soufflant, sans cambrer.',
    muscles: 'Milieu de la poitrine, triceps',
  },
  {
    id: 'pompes-mains-support-25cm',
    code: 'A5',
    name: 'Pompes mains sur support de 25 cm',
    instruction: 'Poitrine au contact du support, dos droit.',
    description: 'Même technique que les pompes sur support de 45 cm, sur un support d’environ 25 cm seulement : le corps est presque horizontal. Mains écartées d’environ 40 cm, pieds au sol. Descendez en inspirant jusqu’à ce que la poitrine touche le support, puis remontez bras tendus en soufflant. Gardez le dos droit, sans cambrer.',
    muscles: 'Milieu de la poitrine, triceps',
  },
  {
    id: 'pompes-mains-pieds-sureleves',
    code: 'A6',
    name: 'Pompes mains et pieds surélevés',
    instruction: 'Poitrine au support, corps bien droit.',
    description: 'Mains (écartées d’environ 40 cm) et pieds sur deux supports de même hauteur, 15 cm au moins, pour descendre plus bas qu’au sol. Corps droit, descendez en inspirant jusqu’à ce que la poitrine touche le support des mains, puis remontez en soufflant. Sans support, faites-les au sol et descendez jusqu’à toucher vos mains. Dos sensible ou tendance à cambrer : préférez le support de 25 cm, mains à 25-30 cm.',
    muscles: 'Milieu de la poitrine, triceps',
  },
  {
    id: 'pompes-chaises-ecart-epaules',
    code: 'A7',
    name: 'Pompes entre chaises, écart des épaules',
    instruction: 'Mains à largeur d’épaules, corps gainé.',
    description: 'Comme les pompes entre chaises, pieds sur une troisième chaise, mais les mains ne sont écartées que de la largeur des épaules. Corps droit et gainé, descendez en inspirant jusqu’à amener la poitrine au niveau des assises, puis remontez bras tendus en soufflant, sans cambrer.',
    muscles: 'Pectoraux, triceps, épaules',
  },
  {
    id: 'pompes-chaises-pieds-au-sol',
    code: 'A8',
    name: 'Pompes entre chaises, pieds au sol',
    instruction: 'Pieds au sol, poitrine entre les chaises.',
    description: 'Mains sur deux chaises écartées de la largeur des épaules, pieds au sol : le corps est incliné, la tête plus haute que les pieds. Corps droit et gainé, descendez en inspirant pour amener la poitrine entre les chaises, puis remontez bras tendus en soufflant. Version plus facile des pompes entre chaises, qui cible le bas des pectoraux.',
    muscles: 'Pectoraux (partie basse)',
  },
  {
    id: 'pompes-serrees-pieds-chaise',
    code: 'A9',
    name: 'Pompes serrées, pieds sur chaise',
    instruction: 'Mains serrées, poitrine au support.',
    description: 'Mains très serrées (15 cm d’écart au plus) sur un support d’environ 20 cm, une brique par exemple, pieds sur une chaise. Corps droit, fléchissez les bras en inspirant jusqu’à toucher le support avec le haut de la poitrine, puis tendez-les en soufflant. Ne cambrez pas. Sans matériel adapté, ou si la position gêne, faites plutôt les pompes pieds sur meuble, mains serrées.',
    muscles: 'Triceps, pectoraux (partie centrale), épaules',
  },
  {
    id: 'pompes-circulaires-chaises',
    code: 'A10',
    name: 'Pompes circulaires entre chaises',
    instruction: 'Tournez autour des épaules en montant et descendant.',
    description: 'Installation des pompes entre chaises, mains à largeur d’épaules, pieds sur une troisième chaise. Au lieu de descendre en ligne droite, faites tourner le corps autour des épaules : partez hanches hautes, avancez les épaules au-dessus des mains, descendez entre les chaises, puis remontez les hanches bras fléchis avant de tendre les bras. Inspirez en descendant, soufflez en remontant.',
    muscles: 'Épaules, pectoraux, triceps',
  },
  {
    id: 'pompes-circulaires-inversees-chaises',
    code: 'A11',
    name: 'Pompes circulaires inversées',
    instruction: 'Plongez vers les mains, remontez par l’avant.',
    description: 'Même installation que les pompes circulaires, cercle dans l’autre sens : depuis la position hanches hautes, plongez la tête vers les mains en fléchissant les bras, glissez la poitrine vers l’avant entre les chaises, tendez les bras corps droit, puis remontez les hanches. Le corps tourne autour des épaules. Inspirez en descendant, soufflez en remontant.',
    muscles: 'Épaules, pectoraux, triceps',
  },
  {
    id: 'pompes-pieds-meuble-mains-serrees',
    code: 'A12',
    name: 'Pompes pieds sur meuble, mains serrées',
    instruction: 'Pieds en hauteur, poitrine vers les chaises.',
    description: 'Deux chaises (ou supports d’environ 45 cm) côte à côte, mains écartées de 40 cm, pieds sur un meuble de 1 m à 1,10 m (table, bureau, étagère…). Gardez le corps droit. Descendez en inspirant jusqu’à approcher la poitrine des assises, puis remontez bras tendus en soufflant. Sans meuble de cette hauteur, prenez un support équivalent : espalier, machine à laver…',
    muscles: 'Pectoraux (partie centrale), triceps, épaules',
  },
  {
    id: 'dips-chaises',
    code: 'B',
    name: 'Dips entre deux chaises',
    instruction: 'Descendez entre les chaises, coudes vers l’arrière.',
    description: 'Mains sur le haut de deux dossiers de chaises (ou de barres parallèles) d’environ 1 m, écartés d’environ 63 cm. Partez bras tendus, jambes fléchies pour que les genoux ne touchent pas le sol. Descendez le plus bas possible en fléchissant les bras et en inspirant, puis remontez bras tendus en soufflant. Vérifiez la solidité des chaises et posez une serviette pliée sous les mains. Tabourets, tréteaux ou meubles de même hauteur conviennent aussi.',
    muscles: 'Pectoraux (partie latérale haute), épaules, triceps',
  },
  {
    id: 'dips-chaises-demi-amplitude',
    code: 'B1',
    name: 'Dips, demi-amplitude',
    instruction: 'Descendez jusqu’aux bras parallèles au sol.',
    description: 'Même installation que les dips entre deux chaises. Partez bras tendus et descendez seulement jusqu’à la moitié du mouvement, quand les bras sont parallèles au sol, puis remontez en tendant les bras. Ne descendez pas plus bas : ce n’est pas le dips complet. Inspirez en descendant, soufflez en remontant.',
    muscles: 'Pectoraux (partie latérale haute), épaules, triceps',
  },
  {
    id: 'dips-chaises-mi-amplitude',
    code: 'B2',
    name: 'Dips, mi-amplitude rapide',
    instruction: 'Petits dips autour des bras parallèles au sol.',
    description: 'Même installation que les dips entre deux chaises. Placez-vous en position mi-descendue, bras parallèles au sol. Descendez un peu sous cette position, puis remontez un peu au-dessus, sans jamais tendre les bras ni descendre à fond. Enchaînez les répétitions le plus vite possible, en inspirant à la descente et en soufflant à la montée.',
    muscles: 'Pectoraux, épaules',
  },
  {
    id: 'tractions-supination',
    code: 'C',
    name: 'Tractions en supination',
    instruction: 'Montez le menton au-dessus de la barre.',
    description: 'Suspendez-vous à une barre fixe, bras tendus, mains à peu près à la largeur des épaules, paumes tournées vers vous. Montez en soufflant jusqu’à passer le menton au-dessus de la barre, puis redescendez en inspirant jusqu’aux bras tendus. Pliez les jambes si vos pieds touchent le sol. Ne tirez pas la tête en arrière pour gagner les derniers centimètres : mieux vaut arrêter la répétition que se blesser la nuque.',
    muscles: 'Milieu du dos, biceps',
  },
  {
    id: 'tractions-supination-moitie-haute',
    code: 'C1',
    name: 'Tractions, moitié haute',
    instruction: 'Du menton à la barre aux bras à mi-course.',
    description: 'Même prise que la traction en supination. Sautez pour démarrer directement en position haute, menton au-dessus de la barre. Descendez en inspirant jusqu’à la moitié du mouvement, quand les bras sont parallèles au sol, puis remontez en soufflant. Sans barre fixe, remplacez par la traction horizontale pieds avancés (C5).',
    muscles: 'Milieu du dos, biceps',
  },
  {
    id: 'tractions-supination-mi-amplitude',
    code: 'C2',
    name: 'Tractions, mi-amplitude rapide',
    instruction: 'Petites tractions à mi-course, bras jamais tendus.',
    description: 'Même prise que la traction en supination. Placez-vous à mi-hauteur, bras parallèles au sol. Descendez un peu sous cette position, puis remontez un peu au-dessus : ne tendez jamais les bras en bas et ne passez pas le menton au-dessus de la barre. Enchaînez le plus vite possible, en inspirant à la descente et en soufflant à la montée. Sans barre fixe, remplacez par C5.',
    muscles: 'Milieu du dos, biceps',
  },
  {
    id: 'tractions-supination-deux-tiers',
    code: 'C3',
    name: 'Tractions, deux tiers d’amplitude',
    instruction: 'Menton au-dessus de la barre, redescendez bras fléchis.',
    description: 'Même technique que la traction en supination, mais sur les deux tiers du mouvement : montez le menton au-dessus de la barre, puis redescendez assez bas en gardant les bras fléchis, sans jamais les tendre. Inspirez en descendant, soufflez en remontant. Sans barre fixe, remplacez par la traction horizontale pieds avancés (C5), puis par C6 si elle devient trop facile.',
    muscles: 'Milieu du dos, biceps',
  },
  {
    id: 'tractions-horizontales-jambes-repliees',
    code: 'C4',
    name: 'Tractions horizontales, jambes repliées',
    instruction: 'Poitrine à la barre, pieds sous les fesses.',
    description: 'Sous une barre solide placée entre 80 et 110 cm (sur deux chaises, tréteaux, table…), prenez-la paumes vers vous, mains un peu plus serrées que les épaules. Pieds rapprochés sous les fesses, genoux bien écartés. En soufflant, tirez jusqu’à toucher la barre avec le bas des pectoraux, haut du dos cambré, sans rejeter la tête en arrière. Redescendez en inspirant, sans élan des reins. Un coussin au sol protège la tête.',
    muscles: 'Épaisseur du dos, biceps',
  },
  {
    id: 'tractions-horizontales-pieds-avances',
    code: 'C5',
    name: 'Tractions horizontales, pieds avancés',
    instruction: 'Corps gainé, tirez la poitrine vers la barre.',
    description: 'Même technique et même respiration que la traction horizontale jambes repliées ; seule la position des jambes change : pieds posés au sol loin devant, genoux fléchis, corps gainé des épaules aux genoux. Tirez la poitrine jusqu’à la barre en soufflant, puis redescendez bras tendus en inspirant, sans que le dos touche le sol. Sans matériel adapté, remplacez temporairement par C8.',
    muscles: 'Épaisseur du dos, biceps',
  },
  {
    id: 'tractions-horizontales-pieds-sureleves',
    code: 'C6',
    name: 'Tractions horizontales, supination, pieds hauts',
    instruction: 'Poitrine à la barre, corps gainé.',
    description: 'Même exécution que les tractions horizontales C4 (barre basse, paumes tournées vers vous, mains un peu moins écartées que les épaules), mais talons posés sur une chaise ou un support d’environ 45 cm, jambes tendues. Corps gainé, tirez jusqu’à toucher la barre avec le bas des pectoraux en soufflant, redescendez bras tendus en inspirant, sans à-coup de reins. Si vous n’avez pas le matériel, remplacez par C9.',
    muscles: 'Épaisseur du dos, biceps',
  },
  {
    id: 'tractions-horizontales-pronation',
    code: 'C7',
    name: 'Tractions horizontales, pronation, genoux pliés',
    instruction: 'Paumes vers l’avant, poitrine à la barre.',
    description: 'Installation de C4 : allongé sous une barre fixée à 80-110 cm du sol, pieds à plat et rapprochés, genoux fléchis et écartés. Seule la prise change : paumes tournées vers l’avant. Tirez jusqu’à amener le haut de la poitrine à la barre en soufflant, sans rejeter la tête en arrière, puis redescendez bras tendus en inspirant. Une table ou un bureau solide peut remplacer la barre.',
    muscles: 'Épaisseur du haut du dos',
  },
  {
    id: 'tractions-horizontales-pronation-pieds-avances',
    code: 'C8',
    name: 'Tractions horizontales, pronation, pieds devant',
    instruction: 'Talons au sol, tirez la poitrine à la barre.',
    description: 'Position de jambes de C5 : jambes allongées loin devant, talons au sol. Prise de C7, paumes tournées vers l’avant. Corps gainé des talons aux épaules, tirez jusqu’à la barre en soufflant, redescendez jusqu’à l’extension des bras en inspirant, sans donner de coup de reins. Barre sur deux chaises, table ou bureau : vérifiez toujours la solidité de l’installation.',
    muscles: 'Épaisseur du haut du dos',
  },
  {
    id: 'tractions-horizontales-pronation-pieds-sureleves',
    code: 'C9',
    name: 'Tractions horizontales, pronation, pieds hauts',
    instruction: 'Pieds surélevés, poitrine à la barre.',
    description: 'La version la plus difficile de la série : talons posés sur un support d’environ 45 cm comme en C6, jambes tendues, et prise de C7, paumes tournées vers l’avant. Corps rigide, tirez jusqu’à toucher la barre avec la poitrine en soufflant, puis redescendez lentement bras tendus en inspirant. Ne cambrez pas et ne lâchez pas la tête en arrière.',
    muscles: 'Épaisseur du haut du dos',
  },
  {
    id: 'dips-dos-chaise-pieds-sureleves',
    code: 'D',
    name: 'Dips dos à la chaise, pieds surélevés',
    instruction: 'Pliez les bras, descendez, puis tendez-les.',
    description: 'Deux chaises face à face, à environ un mètre. Dos à l’une, agrippez les bords gauche et droit de l’assise ; talons presque joints sur l’autre chaise, jambes légèrement fléchies. Pliez les bras en inspirant pour descendre le bassin le plus bas possible, puis tendez-les en soufflant pour remonter. Les premières fois, limitez la descente : un manque de souplesse peut blesser les épaules.',
    muscles: 'Triceps',
  },
  {
    id: 'squat-une-jambe-assiste-petite-flexion',
    code: 'E',
    name: 'Squat une jambe, petite flexion',
    instruction: 'Petite flexion sur une jambe, remontez jambe tendue.',
    description: 'Debout dans un cadre de porte, mains posées sur les montants à hauteur de la taille, sans serrer : ils ne servent qu’à l’équilibre. Sur une jambe, l’autre tenue devant, fléchissez peu, nettement moins que la cuisse parallèle au sol, en inspirant, puis remontez jambe tendue en soufflant. Faites toute la série d’une jambe, reposez-vous 2 à 3 minutes, puis passez à l’autre.',
    muscles: 'Cuisses, fessiers',
  },
  {
    id: 'squat-une-jambe-assiste-cuisse-parallele',
    code: 'E1',
    name: 'Squat une jambe, cuisse parallèle',
    instruction: 'Descendez jusqu’à la cuisse parallèle au sol.',
    description: 'Même installation que E, mains légèrement posées sur les montants de la porte (ou de part et d’autre d’un poteau). Sur une jambe, descendez en inspirant jusqu’à ce que la cuisse soit parallèle au sol, puis remontez en soufflant. La jambe libre, un peu fléchie, reste levée devant sans toucher le sol. Dos plutôt droit, penché vers l’avant sans cambrer ; pas de coup de reins en fin de montée.',
    muscles: 'Cuisses, fessiers',
  },
  {
    id: 'squat-une-jambe-assiste-flexion-complete',
    code: 'E2',
    name: 'Squat une jambe, flexion complète',
    instruction: 'Descendez au plus bas, remontez jambe tendue.',
    description: 'Technique de E1, mais en amplitude complète : sur une jambe, mains posées sur le cadre de la porte, descendez le plus bas possible en inspirant, la jambe libre tendue devant sans toucher le sol, puis remontez jusqu’à la jambe tendue en soufflant. Gardez le dos droit et ne tirez pas sur les bras. Travaillez une jambe entière, puis l’autre après 2 à 3 minutes de repos.',
    muscles: 'Cuisses, fessiers',
  },
  {
    id: 'squat-une-jambe-assiste-rebonds',
    code: 'E3',
    name: 'Squat une jambe en rebonds',
    instruction: 'Rebonds rapides en bas, sans tendre la jambe.',
    description: 'Installation de E1. Sur une jambe, descendez un peu sous la cuisse parallèle, sans aller tout en bas, puis remontez sans tendre la jambe et redescendez aussitôt : enchaînez des rebonds rapides sans jamais vous relever complètement. Inspirez en descendant, soufflez en remontant. La jambe libre ne touche jamais le sol. Une jambe, repos de 2 à 3 minutes, puis l’autre.',
    muscles: 'Cuisses, fessiers',
  },
  {
    id: 'fente-laterale-alternee',
    code: 'E4',
    name: 'Fente latérale alternée',
    instruction: 'Fléchissez une jambe, l’autre reste tendue.',
    description: 'Debout, jambes très écartées. Fléchissez la jambe droite et descendez le plus bas possible en gardant la gauche bien tendue, puis remontez. Faites de même de l’autre côté, et continuez en alternant. Inspirez en descendant, soufflez en remontant. Tenez l’exercice le plus longtemps possible sans pause, en visant à terme trois minutes d’affilée.',
    muscles: 'Cuisses, fessiers',
  },
  {
    id: 'fente-laterale-un-cote',
    code: 'E5',
    name: 'Fente latérale, un côté par série',
    instruction: 'Toujours la même jambe fléchie, l’autre tendue.',
    description: 'Même fente latérale que l’exercice alterné, mais toute la série se fait du même côté : fléchissez uniquement la jambe droite, la gauche restant tendue, sans vous arrêter. Visez progressivement trois minutes d’affilée. Reposez-vous une minute trente au plus, puis enchaînez trois minutes en fléchissant cette fois uniquement la jambe gauche.',
    muscles: 'Cuisses, fessiers',
  },
  {
    id: 'squat-complet-pieds-serres',
    code: 'E6',
    name: 'Squat complet pieds serrés',
    instruction: 'Descendez au plus bas, tenez deux secondes.',
    description: 'Debout, pieds serrés et parallèles, bras tendus devant vous. Pliez les jambes en inspirant et descendez le plus bas possible, restez deux secondes en bas pour étirer les cuisses, puis remontez. Enchaînez pendant une minute, sans compter. Sans pause, écartez ensuite un peu les pieds, pointes vers l’extérieur, et faites une seconde minute de la même façon, toujours au plus bas.',
    muscles: 'Cuisses, fessiers',
  },
  {
    id: 'squat-une-jambe-dos-au-mur',
    code: 'E7',
    name: 'Squat sur une jambe dos au mur',
    instruction: 'Descendez sur une jambe, doigts effleurant le mur.',
    description: 'Dos à un mur, un pas devant lui, en équilibre sur une jambe, l’autre légèrement fléchie devant vous sans toucher le sol. Laissez-vous descendre sous la parallèle, sans plier complètement la jambe. En bas, le bout des doigts touche le mur un instant pour vous équilibrer et donner une légère impulsion ; la cuisse assure l’essentiel de la remontée et la termine seule. Gardez le buste droit, sans le tordre.',
    muscles: 'Cuisses, fessiers',
  },
  {
    id: 'sauts-verticaux-flexion',
    code: 'F',
    name: 'Sauts verticaux avec flexion',
    instruction: 'Rebondissez dès que les cuisses sont parallèles.',
    description: 'Sautez le plus verticalement possible. Recevez-vous sur l’avant du pied, jamais à plat ni sur les talons, et amortissez en pliant les jambes jusqu’aux cuisses parallèles au sol. Sans temps d’arrêt, détendez-vous comme un ressort pour repartir. En l’air, gardez les jambes légèrement fléchies : ne les tendez pas brutalement, pour ménager le bas du dos. Ne vous réceptionnez jamais jambes tendues.',
    muscles: 'Cuisses, mollets',
  },
  {
    id: 'chaise-contre-mur',
    code: 'F1',
    name: 'Chaise contre le mur',
    instruction: 'Dos au mur, cuisses parallèles au sol, tenez.',
    description: 'Dos plaqué contre un mur, glissez jusqu’à ce que vos cuisses soient parallèles au sol, genoux au-dessus des chevilles, comme assis sur une chaise invisible. Restez immobile le plus longtemps possible. Allongez la durée au fil des séances jusqu’à tenir trois minutes.',
    muscles: 'Cuisses, mollets',
  },
  {
    id: 'squat-ecarte-maintien',
    code: 'F2',
    name: 'Squat écarté tenu',
    instruction: 'Jambes écartées, cuisses presque à l’horizontale.',
    description: 'Debout, jambes largement écartées, dos bien droit. Fléchissez jusqu’à ce que vos cuisses soient presque parallèles au sol, mains posées sur les cuisses, et gardez cette position le plus longtemps possible. Semaine après semaine, visez trois minutes d’affilée.',
    muscles: 'Cuisses, mollets',
  },
  {
    id: 'chaise-contre-mur-une-jambe',
    code: 'F3',
    name: 'Chaise contre le mur sur une jambe',
    instruction: 'Cheville posée sur le genou d’appui, tenez.',
    description: 'Variante plus difficile de la chaise contre le mur : dos au mur, cuisse d’appui parallèle au sol, un seul pied posé. Placez la cheville de l’autre jambe sur le genou de la jambe d’appui et tenez le plus longtemps possible, puis changez de jambe. Objectif à terme : trois minutes d’affilée de chaque côté.',
    muscles: 'Cuisses, mollets',
  },
  {
    id: 'crunch-jambes-relevees',
    code: 'G',
    name: 'Crunch jambes relevées',
    instruction: 'Enroulez le buste, bas du dos au sol.',
    description: 'Allongé sur le dos, cuisses repliées presque à angle droit avec le sol. En soufflant, enroulez le buste pour rapprocher la poitrine du bassin, ventre rentré, sans décoller le bas du dos ni vous aider des hanches. Inspirez en revenant. Ne tirez pas sur la nuque avec les mains. Variantes : pieds à plat au sol jambes pliées, ou mollets posés sur une chaise pour stabiliser les cuisses.',
    muscles: 'Abdominaux partie haute',
  },
  {
    id: 'releve-genoux-suspendu',
    code: 'H',
    name: 'Relevé de genoux suspendu',
    instruction: 'Genoux vers la poitrine, ventre rentré.',
    description: 'Suspendu à une barre, jambes pliées. En inspirant, ramenez les genoux vers la poitrine, ventre rentré. Redescendez en soufflant jusqu’à ce que les cuisses soient parallèles au sol, sans relâcher le ventre et en gardant les jambes pliées, puis remontez. Si vous ne pouvez pas vous suspendre, remplacez cet exercice par P, ou par O si P est trop difficile.',
    muscles: 'Abdominaux partie basse',
  },
  {
    id: 'tractions-nuque-petite-amplitude',
    code: 'I',
    name: 'Tractions nuque, petite amplitude',
    instruction: 'Nuque à la barre, descendez à peine.',
    description: 'Suspendu à une barre fixe (1,80 m au moins), paumes vers l’avant, mains écartées de près de deux largeurs d’épaules. Tirez avec le dos et les bras jusqu’à poser la nuque contre la barre, puis ne redescendez que de quelques centimètres avant de remonter, à un rythme rapide. Inspirez en descendant, soufflez en montant. Pour la première répétition, aidez-vous d’un petit saut ou d’une chaise. Les pieds ne touchent jamais le sol : pliez les jambes.',
    muscles: 'Largeur du dos',
  },
  {
    id: 'tractions-nuque-mi-amplitude',
    code: 'I1',
    name: 'Tractions nuque, demi-amplitude',
    instruction: 'Descendez jusqu’aux bras parallèles au sol.',
    description: 'Même installation que l’exercice I : prise large, paumes vers l’avant, suspendu à la barre fixe. Montez jusqu’à ce que la nuque touche la barre, puis descendez seulement jusqu’à ce que vos bras (du coude à l’épaule) soient à l’horizontale, jamais plus bas. Remontez aussitôt, le plus vite possible. Inspirez à la descente, soufflez à la montée. Les pieds restent décollés du sol.',
    muscles: 'Largeur du dos',
  },
  {
    id: 'tractions-nuque-amplitude-complete',
    code: 'I2',
    name: 'Tractions nuque, amplitude complète',
    instruction: 'Bras tendus en bas, nuque à la barre en haut.',
    description: 'Suspendu à la barre fixe, prise large (près de deux largeurs d’épaules), paumes vers l’avant. Partez bras complètement tendus et tirez jusqu’à ce que la nuque vienne au contact de la barre, tête légèrement penchée en avant. Redescendez de façon contrôlée jusqu’à l’extension complète des bras. Inspirez en descendant, soufflez en montant. Pliez les jambes si nécessaire pour ne pas toucher le sol.',
    muscles: 'Largeur du dos',
  },
  {
    id: 'tractions-pronation-prise-epaules',
    code: 'I3',
    name: 'Tractions pronation, prise épaules',
    instruction: 'Paumes vers l’avant, menton au-dessus de la barre.',
    description: 'Mains sur la barre à largeur d’épaules environ, paumes tournées vers l’avant (et non vers vous comme pour C). Partez bras tendus et montez jusqu’à passer le menton au-dessus de la barre, sans rejeter la tête en arrière. Adaptez l’amplitude à votre besoin : complète, moitié ou deux tiers. Inspirez en descendant, soufflez en montant. Si vous l’utilisez à la place de I, I1 ou I2 faute de barre longue, reprenez leur amplitude.',
    muscles: 'Dos, bras',
  },
  {
    id: 'tractions-prise-large-menton',
    code: 'I4',
    name: 'Tractions prise large, menton',
    instruction: 'Prise large, menton au-dessus de la barre.',
    description: 'Comme l’exercice I2 (prise large, paumes vers l’avant, départ bras tendus), mais vous montez devant la barre : tirez jusqu’à ce que le menton passe au-dessus. Ne basculez pas la tête en arrière pour gagner les derniers centimètres, vos cervicales en souffriraient. Redescendez jusqu’aux bras tendus. Inspirez en descendant, soufflez en montant. Sans barre fixe, remplacez cet exercice par I8.',
    muscles: 'Largeur du dos',
  },
  {
    id: 'tractions-prise-neutre-serree',
    code: 'I5',
    name: 'Tractions prise neutre serrée',
    instruction: 'Paumes face à face, menton au-dessus de la barre.',
    description: 'Technique de l’exercice I4, mais les mains sont rapprochées, paumes face à face (prise neutre). Descendez jusqu’aux bras complètement tendus en inspirant, puis montez le menton au-dessus de la barre en soufflant. Sur une barre longue coincée entre deux murs, sans montants où s’accrocher, passez deux sangles ou deux anneaux autour de la barre. À défaut, remplacez par I3 ou, mieux, par I6.',
    muscles: 'Dos, bras',
  },
  {
    id: 'tractions-horizontales-prise-neutre',
    code: 'I6',
    name: 'Tractions horizontales, prise neutre',
    instruction: 'Tirez la poitrine à la barre, corps gainé.',
    description: 'Allongé sous une barre posée entre deux chaises (ou sous une table), saisissez-la paumes face à face, par exemple avec deux sangles. Tirez jusqu’à toucher la barre avec le bas des pectoraux, haut du dos cambré, tête dans l’axe, puis redescendez bras tendus. Inspirez en descendant, soufflez en montant. Niveaux : genoux fléchis (débutant), jambes tendues (entraîné), pieds surélevés (confirmé) ; passez au suivant au-delà de 15 répétitions.',
    muscles: 'Épaisseur du dos',
  },
  {
    id: 'tractions-nuque-deux-tiers',
    code: 'I7',
    name: 'Tractions nuque, deux tiers d’amplitude',
    instruction: 'Descendez jusqu’aux bras presque tendus.',
    description: 'Version plus ample de l’exercice I1 : prise large, paumes vers l’avant, montez jusqu’à amener la nuque contre la barre, puis descendez sur les deux tiers du mouvement complet, jusqu’aux bras presque tendus, sans aller à l’extension totale. Remontez sans marquer d’arrêt. Inspirez en descendant, soufflez en remontant. Les pieds restent décollés du sol.',
    muscles: 'Largeur du dos',
  },
  {
    id: 'tractions-horizontales-prise-large',
    code: 'I8',
    name: 'Tractions horizontales, prise large',
    instruction: 'Prise large, poitrine à la barre.',
    description: 'Même installation et même respiration que le tirage C4 : allongé sous une barre fixée entre deux chaises (ou sous une table, un bureau), mais mains écartées d’environ deux largeurs d’épaules, paumes vers l’avant. Corps gainé, tirez jusqu’à amener la poitrine contre la barre, puis redescendez lentement bras tendus. Inspirez en descendant, soufflez en montant. Progressez des genoux fléchis aux jambes tendues, puis aux pieds surélevés.',
    muscles: 'Épaisseur du haut du dos',
  },
  {
    id: 'pompes-piquees-chaises',
    code: 'J',
    name: 'Pompes piquées pieds surélevés',
    instruction: 'Fesses hautes, descendez la tête entre les chaises.',
    description: 'Pointes de pieds au bord d’un meuble d’environ 1 m, mains à plat sur deux chaises à assise ferme, écartées d’environ deux largeurs d’épaules. Corps plié, fesses pointées vers le plafond. Descendez la tête le plus bas possible entre les chaises en inspirant, remontez en soufflant. Évitez un dos trop vertical, qui fait basculer ; calez les pieds contre le mur s’ils glissent. Écart mains-pieds : environ 1,05 m pour 1,80 m.',
    muscles: 'Épaules, partie supérieure des pectoraux',
  },
  {
    id: 'pompes-piquees-chaises-mains-serrees',
    code: 'J1',
    name: 'Pompes piquées mains rapprochées',
    instruction: 'Mains rapprochées, fesses hautes, tête vers le bas.',
    description: 'Même installation que les pompes piquées pieds surélevés (J) : pieds sur un meuble d’environ 1 m, mains sur deux chaises, fesses vers le plafond. Cette fois, les mains ne sont qu’un peu plus écartées que les épaules. Descendez la tête le plus bas possible en inspirant, remontez en soufflant, sans laisser le dos devenir trop vertical. Plus difficile que J.',
    muscles: 'Épaules, partie supérieure des pectoraux',
  },
  {
    id: 'pompes-piquees-chaises-poings',
    code: 'J2',
    name: 'Pompes piquées sur les poings',
    instruction: 'Sur les poings, fesses hautes, tête vers le bas.',
    description: 'Comme les pompes piquées pieds surélevés (J), mains écartées d’environ deux largeurs d’épaules, mais en appui sur les poings fermés, alignés comme si vous teniez une barre. Posez une serviette pliée ou un coussin fin sur l’assise si le contact fait mal. Descendez la tête le plus bas possible en inspirant, remontez en soufflant.',
    muscles: 'Épaules, partie supérieure des pectoraux',
  },
  {
    id: 'pompes-piquees-chaises-poings-serres',
    code: 'J3',
    name: 'Pompes piquées poings rapprochés',
    instruction: 'Poings rapprochés, fesses hautes, tête vers le bas.',
    description: 'Variante mains rapprochées (J1) exécutée sur les poings : pieds sur un meuble d’environ 1 m, poings sur deux chaises à peine plus écartés que les épaules, alignés, sur une serviette pliée si besoin. Fesses vers le plafond, descendez la tête le plus bas possible en inspirant, remontez en soufflant. La plus difficile des quatre variantes.',
    muscles: 'Épaules, partie supérieure des pectoraux',
  },
  {
    id: 'extensions-triceps-avant-bras-sol',
    code: 'K',
    name: 'Extensions triceps sur les avant-bras',
    instruction: 'Paumes au sol, tendez les bras sans cambrer.',
    description: 'En planche sur les pointes de pieds, coudes au sol à largeur d’épaules, mains à plat un peu devant la tête et légèrement moins écartées que les coudes. Sans décoller les paumes, tendez les bras en soufflant, puis revenez sur les avant-bras en inspirant. Coudes serrés, reins jamais cambrés. Progressez en amplitude : 1/3, 1/2, 2/3 puis complète. Trop dur ? Avant-bras sur un support d’environ 40 cm, pieds au sol.',
    muscles: 'Triceps',
  },
  {
    id: 'extensions-triceps-table',
    code: 'K1',
    name: 'Extensions triceps à la table',
    instruction: 'Fléchissez les bras, tête sous le bord de la table.',
    description: 'Mains au bord d’une table, d’un bureau solide ou d’une barre fixe à environ 1 m du sol, sur la pointe des pieds à environ 1,30 m du support, corps droit. Pliez complètement les bras pour amener la tête sous le bord, puis remontez en tendant les bras, sans à-coup. Après 20 répétitions, prenez un support 20 cm plus bas (80 cm, puis 60 cm…) ; à défaut, surélevez les pieds ou ralentissez le rythme.',
    muscles: 'Triceps',
  },
  {
    id: 'extensions-triceps-mur-chaise',
    code: 'K2',
    name: 'Extensions triceps mur puis chaise',
    instruction: 'Pliez les bras jusqu’à poser les avant-bras.',
    description: 'Six niveaux. 1 : face à un mur, mains à 1,50 m, sur la pointe des pieds ; fléchissez jusqu’à toucher le mur du front et des avant-bras, et descendez les mains de 10 cm après 15 répétitions. Puis mains sur une chaise de 45 cm calée au mur, jambes très écartées (2), moyennement (3), serrées genoux un peu fléchis (4), pieds sur une cale de 20 cm (5), puis cale plus haute (6). Passez au niveau suivant à 20-25 répétitions. Sans à-coup.',
    muscles: 'Triceps',
  },
  {
    id: 'extensions-triceps-barre-chaises',
    code: 'K3',
    name: 'Extensions triceps barre entre chaises',
    instruction: 'Paumes vers vous, pliez les bras sous la barre.',
    description: 'Comme l’extension à la table, mais les mains tiennent en supination (paumes vers vous) une barre attachée par un nœud simple entre les dossiers de deux chaises calées contre un mur, ou une sangle tendue à environ 45 cm du sol. Corps droit sur la pointe des pieds, pliez les bras pour passer la tête sous la barre, puis tendez-les. Jambes très écartées au début, puis de plus en plus serrées ; ensuite, ralentissez le rythme.',
    muscles: 'Triceps',
  },
  {
    id: 'pompes-rotation-alternee',
    code: 'L',
    name: 'Pompes avec rotation alternée',
    instruction: 'Basculez le poids sur un bras, puis sur l’autre.',
    description: 'En appui sur les mains, corps gainé et pointes de pieds au sol, comme pour une pompe classique. En inspirant, descendez en faisant pivoter le buste d’un côté : le poids passe sur le bras qui plie. Remontez en soufflant jusqu’à la position de départ, puis faites la répétition suivante de l’autre côté. Alternez ainsi droite et gauche toute la série et descendez aussi bas que possible.',
    muscles: 'Pectoraux, épaules, triceps',
  },
  {
    id: 'extensions-lombaires-support',
    code: 'M',
    name: 'Extensions lombaires sur support',
    instruction: 'Buste vers le sol, remontez à l’horizontale.',
    description: 'À plat ventre sur un support stable d’environ 110 cm (meuble, tréteau), hanches juste au-delà du bord, chevilles maintenues (sangle, meuble lourd ou partenaire). Mains sur la nuque ou bras tendus, descendez le buste vers le sol en soufflant, puis remontez en inspirant jusqu’à l’horizontale, pas au-delà. Les pieds ne doivent jamais être plus hauts que les fesses. Une couverture protège le support ; à défaut, faites M1.',
    muscles: 'Bas du dos',
  },
  {
    id: 'inclinaisons-buste-bras-tendus',
    code: 'M1',
    name: 'Inclinaisons du buste bras tendus',
    instruction: 'Dos droit, buste penché jusqu’à l’horizontale.',
    description: 'Debout, genoux légèrement fléchis, bras tendus dans le prolongement du buste. Penchez-vous en avant, dos droit (mieux vaut le cambrer un peu que l’arrondir), jusqu’à ce que le buste soit parallèle au sol, puis remontez et arrêtez-vous à la verticale, sans basculer en arrière. Soufflez en descendant, inspirez en montant. Au-delà de 50 répétitions, ralentissez : par exemple 10 s de descente, 10 s de maintien à l’horizontale, 1 s pour remonter.',
    muscles: 'Bas du dos',
  },
  {
    id: 'flexions-laterales-support',
    code: 'N',
    name: 'Flexions latérales sur support',
    instruction: 'Buste vers le sol, puis remontez au plus haut.',
    description: 'Couché sur le côté sur un support d’au moins 40 cm (banc, chaise, bord de lit), le buste dépasse à partir des hanches et les pieds sont bloqués (montant de lit, partenaire, sangle). Inspirez en inclinant le buste vers le sol, puis soufflez en le remontant le plus haut possible. Les premières semaines, ne descendez pas trop bas et augmentez l’amplitude peu à peu. Sans support adapté, faites N1 au sol.',
    muscles: 'Obliques',
  },
  {
    id: 'releves-lateraux-sol',
    code: 'N1',
    name: 'Relevés latéraux au sol',
    instruction: 'Sur le côté, décollez le buste sans élan.',
    description: 'Allongé sur le côté, de préférence sur un tapis, jambes tendues l’une sur l’autre, main du dessus derrière la tête. Décollez le buste du sol en l’inclinant sur le côté, sans à-coups ni élan, aussi haut que possible, puis redescendez en contrôlant le mouvement. Soufflez en montant, inspirez en descendant. Changez de côté à la série suivante.',
    muscles: 'Obliques',
  },
  {
    id: 'releve-buste-rotation',
    code: 'O',
    name: 'Relevé de buste avec rotation',
    instruction: 'Coude vers le genou opposé, en alternant.',
    description: 'Allongé sur le dos, genoux pliés, pieds à plat. En soufflant, enroulez le buste en tournant pour amener le coude droit vers le genou gauche, puis redescendez en inspirant sans reposer complètement les épaules. À la répétition suivante, coude gauche vers genou droit. Rentrez le ventre toute la série et ne tirez jamais sur la nuque. Débutez en vous aidant des bras tendus vers l’avant, puis mains derrière la nuque dès 16 répétitions (8 par côté).',
    muscles: 'Abdominaux, obliques',
  },
  {
    id: 'releve-buste',
    code: 'P',
    name: 'Relevé de buste',
    instruction: 'Enroulez-vous jusqu’aux cuisses, ventre rentré.',
    description: 'Allongé sur le dos, genoux fléchis, pieds bien à plat. En soufflant, enroulez le buste jusqu’à venir toucher les cuisses, puis redescendez en inspirant sans reposer les épaules au sol. Rentrez le ventre toute la série, ne bloquez pas la respiration et ne creusez pas les reins pour vous aider. Débutez en vous aidant des bras tendus vers l’avant ; dès 15 répétitions, placez les mains derrière la nuque, sans tirer dessus.',
    muscles: 'Abdominaux',
  },
  {
    id: 'pompes-un-bras-chaise',
    code: 'Q',
    name: 'Pompes sur un bras sur une chaise',
    instruction: 'Descendez l’épaule à hauteur de la main.',
    description: 'Une main en appui sur une chaise, jambes tendues et écartées, sur la pointe des pieds placés un peu en arrière des hanches. Fléchissez le bras en inspirant jusqu’à amener l’épaule à hauteur de la main, pas plus bas, puis poussez en soufflant. Dos droit, sans reculer les fesses ni vous tordre : l’épaule et le bras font le travail. Trop dur : appui plus haut (1 m, puis 70 cm) ; à 20 répétitions, passez au support suivant.',
    muscles: 'Épaules, triceps, pectoraux (partie latérale haute)',
  },
  {
    id: 'pompes-un-bras-support-bas',
    code: 'Q1',
    name: 'Pompes sur un bras, support de 25 cm',
    instruction: 'Corps droit, descendez sur un bras.',
    description: 'Même mouvement que sur la chaise, main sur un support d’environ 25 cm. Gardez le corps aussi droit que possible : la jambe du côté du bras d’appui est tendue dans son prolongement, l’autre, écartée presque à l’équerre, assure l’équilibre (vous pouvez aussi la ramener vers l’avant). Inspirez en descendant le plus bas possible sans trop étirer l’épaule, soufflez en remontant par la force du bras, sans vous jeter en arrière.',
    muscles: 'Épaules, triceps, pectoraux (partie latérale haute)',
  },
  {
    id: 'pompes-un-bras-sol',
    code: 'Q2',
    name: 'Pompes sur un bras au sol',
    instruction: 'Une main au sol, corps droit, descendez.',
    description: 'Même technique que sur le support de 25 cm, mais main posée directement au sol. La jambe du côté du bras d’appui est tendue dans l’axe du corps, l’autre écartée ou ramenée vers l’avant pour l’équilibre, selon votre confort. Inspirez en descendant sans vous laisser tomber ni trop étirer l’épaule, soufflez en remontant en poussant avec l’épaule et le bras, sans vous tordre.',
    muscles: 'Épaules, triceps, pectoraux (partie latérale haute)',
  },
  {
    id: 'haussements-epaules-appui',
    code: 'R',
    name: 'Haussements d’épaules en appui',
    instruction: 'Bras tendus, abaissez les épaules loin des oreilles.',
    description: 'Placez-vous entre deux chaises hautes (ou des barres parallèles), mains sur les dossiers, bras tendus, pieds décollés du sol. Haussez les épaules vers les oreilles en inspirant : le corps descend. Abaissez-les ensuite le plus bas possible en soufflant : le corps remonte entre les bras. Travaillez lentement, concentré, avec une respiration profonde, en cherchant à descendre les épaules un peu plus à chaque répétition.',
    muscles: 'Trapèzes, cou',
  },
  {
    id: 'flexion-cou-allonge-banc',
    code: 'S',
    name: 'Flexion du cou, allongé sur un banc',
    instruction: 'Tête en arrière, puis menton vers la poitrine.',
    description: 'Allongez-vous sur le dos sur un banc ou une chaise, la tête dans le vide, les pieds au sol. Laissez descendre la tête en arrière en inspirant, le plus bas possible sans forcer sur les cervicales, puis remontez-la en soufflant, menton vers la poitrine. Deux séries au maximum de répétitions, 40 s de repos, sans rythme rapide. Si cela devient facile, ralentissez : 5 à 10 s pour monter comme pour descendre.',
    muscles: 'Cou',
  },
  {
    id: 'rotations-buste-assis-sol-baton',
    code: 'T',
    name: 'Rotations du buste assis au sol, bâton',
    instruction: 'Tournez le buste, cuisses et fesses immobiles.',
    description: 'Assis au sol, jambes fléchies, pieds à plat et si possible calés sous un meuble, placez un manche à balai derrière les épaules. Tournez le buste à droite puis à gauche, aussi loin que possible sans forcer. Cuisses et fesses ne bougent pas, le ventre reste rentré, le bas du dos ne se creuse jamais ; respirez librement. Visez trois minutes sans pause, puis penchez-vous peu à peu davantage en arrière.',
    muscles: 'Obliques, abdominaux',
  },
  {
    id: 'charrue-enroulement-dos',
    code: 'U',
    name: 'Charrue (enroulement du dos)',
    instruction: 'Enroulez le dos, pieds par-dessus la tête.',
    description: 'Allongé sur un tapis (une serviette pliée sous les épaules et la tête si besoin), montez les jambes presque tendues au-dessus du ventre, reins plaqués au sol. Enroulez lentement la colonne pour faire passer les pieds par-dessus la tête, sans élan ; avec la souplesse, ils toucheront le sol derrière. Revenez sans que les reins se creusent. Respirez plusieurs fois à chaque phase et visez trois minutes sans pause.',
    muscles: 'Abdominaux, souplesse de la colonne vertébrale',
  },
  {
    id: 'essuie-glace-jambes',
    code: 'V',
    name: 'Essuie-glace, jambes presque tendues',
    instruction: 'Jambes d’un côté puis de l’autre, sans creuser.',
    description: 'Allongé sur le dos, bras écartés au sol, levez les jambes presque tendues à la verticale. Descendez-les d’un côté puis de l’autre, comme un essuie-glace, pendant trois minutes. Ramenez le bassin vers la tête, fesses légèrement décollées, pour ne jamais creuser les reins, surtout en descendant. Respirez librement à chaque passage. Au début l’amplitude sera faible : ne forcez pas, elle viendra avec le temps.',
    muscles: 'Muscles de la taille, souplesse de la colonne vertébrale',
  },
  {
    id: 'mollet-une-jambe-sur-cale',
    code: 'W',
    name: 'Mollet sur une jambe, sur une cale',
    instruction: 'Talon bas, puis montez sur la pointe du pied.',
    description: 'Debout sur une cale d’au moins 15 cm, en appui sur l’avant d’un seul pied, talon dans le vide, l’autre jambe repliée. Le bout des doigts posé contre un mur assure l’équilibre. Descendez le talon le plus bas possible pour étirer le mollet, puis montez sur la pointe par la seule force du mollet. Allez lentement pour sentir l’étirement et la contraction complets. Travaillez le mollet droit, puis le gauche.',
    muscles: 'Mollets',
  },
  {
    id: 'rotations-buste-tabouret-baton',
    code: 'X',
    name: 'Rotations du buste sur tabouret, bâton',
    instruction: 'Tournez lentement le buste, bassin immobile.',
    description: 'Assis sur un tabouret ou une chaise assez haute (ou debout), jambes écartées, tenez un manche à balai derrière les épaules. Tournez lentement le buste vers la droite puis vers la gauche, de façon régulière et sans pause, le bassin immobile. Arrêtez-vous dès la première résistance, sans jamais forcer. Rentrez un peu le ventre, penchez-vous légèrement en avant et ne creusez pas les reins. L’amplitude progressera avec le temps.',
    muscles: 'Muscles de la taille, souplesse de la colonne vertébrale',
  },
  {
    id: 'rotation-tete-allonge-cote',
    code: 'Y',
    name: 'Rotation de la tête, allongé sur le côté',
    instruction: 'Tournez lentement la tête vers le plafond.',
    description: 'Allongez-vous sur le côté sur un tapis, un coussin épais sous les côtes, le bras du dessous étendu au sol dans le prolongement du corps. Couché sur le côté droit, tournez lentement la tête vers la gauche, vers le plafond, aussi loin que possible sans jamais forcer, puis ramenez-la en la tournant légèrement vers le sol. Dix répétitions très lentes au plus ; une série sur chaque côté.',
    muscles: 'Cou',
  },
  {
    id: 'pont-arriere-roue',
    code: 'Z',
    name: 'Pont arrière (roue)',
    instruction: 'Poussez sur les bras, dos arqué.',
    description: 'Allongé sur le dos, genoux fléchis, pieds parallèles ; mains à plat près des oreilles, doigts vers les pieds. Soulevez les hanches et poussez sur les bras pour poser le sommet du crâne au sol, puis tendez les bras en arquant le haut du dos. Tenez en ramenant le menton vers la poitrine, puis redescendez par l’étape 2. Sol non glissant, paumes bien plaquées, jamais de force sur le bas du dos.',
    muscles: 'Souplesse de la colonne vertébrale',
  },
  {
    id: 'abdominaux',
    name: 'Crunch',
    instruction: 'Enroulez le buste, bas du dos au sol.',
    description: 'Allongé sur le dos, genoux fléchis, pieds à plat, mains aux tempes. Enroulez le haut du buste en décollant les épaules, sans tirer sur la nuque et en gardant le bas du dos au sol, puis redescendez lentement. Soufflez en montant.',
    muscles: 'Grand droit de l’abdomen',
  },
  {
    id: 'abdominaux-lateraux',
    name: 'Crunch croisé',
    instruction: 'Coude vers le genou opposé, en alternant.',
    description: 'Allongé sur le dos, genoux relevés, mains aux tempes. Relevez le buste en rotation pour amener un coude vers le genou opposé, qui vient à sa rencontre, puis revenez et changez de côté. Gardez le bas du dos au sol.',
    muscles: 'Obliques, grand droit de l’abdomen',
  },
  {
    id: 'kettlebell-swing',
    name: 'Kettlebell swing',
    instruction: 'Extension explosive des hanches, dos gainé.',
    description: 'Debout, pieds un peu plus écartés que les hanches, kettlebell tenue à deux mains. Reculez les hanches, dos plat, pour faire passer la kettlebell entre les jambes, puis tendez les hanches d’un coup pour la projeter à hauteur d’épaules, bras tendus. Ce sont les hanches qui travaillent, pas les bras.',
    muscles: 'Fessiers, ischio-jambiers, lombaires, sangle abdominale',
  },
  {
    id: 'hand-gripper',
    name: 'Hand gripper',
    instruction: 'Serrez à fond, relâchez lentement.',
    description: 'Pince tenue dans la paume, poignée fixe contre la base du pouce. Serrez jusqu’à ce que les poignées se touchent, marquez un temps, puis relâchez lentement. Faites la série d’une main, puis de l’autre.',
    muscles: 'Fléchisseurs des doigts, avant-bras',
  },
];
